[package]
name = "commit-triage"
version = "0.1.0"
edition = "2024"

[dependencies]
ammonia = "4.1.2"
clap = { version = "4.6.0", features = ["derive"] }
comrak = "0.52.0"
crossterm = { version = "0.29.0", features = ["event-stream"] }
futures = "0.3.32"
ratatui = { version = "0.30.0", default-features = false, features = ["crossterm"] }
rocket = "0.5.1"
rocket_ws = "0.1.1"
tokio = { version = "1.50.0", features = ["macros", "rt-multi-thread"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
#tui-popup = { version = "0.7.2", features = ["crossterm"] }
